# a way to force release all the services through content in release note
# release all the services if its a first uat or prod release
name: Release

on:
  release:
    types: [published]

jobs:
  release-all:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: All
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get latest release info
        id: latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - name: Get sha of this release
        id: vars
        run: |
          env=$(awk -F- '{print $2}' <<< '${{steps.latest-release.outputs.tag_name}}')
          echo $env
          echo ::set-output name=this_sha::$(git rev-list -n 1 $(git tag | grep $env | sed '1!G;h;$!d' | head -n 1))
          echo ::set-output name=that_sha::$(git rev-list -n 1 $(git tag | grep $env | sed '1!G;h;$!d' | head -n 2 | tail -1))

      - name: Deploy
        run: |
          nx affected --target=deploy --base={{steps.vars.outputs.that_sha}} --head={{steps.vars.outputs.this_sha}}
