# a way to force release all the services through content in release note
# release all the services if its a first uat or prod release
name: Release

on:
  release:
    types: [published]

jobs:
  release-all:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: All
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Instal dependencies
        run: |
          npm install -g nx
          npm ci

      - name: Get latest release info
        id: latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - name: Get sha of this release
        id: vars
        run: |
          if [[ "${{steps.latest-release.outputs.body}}" = "all" ]] ; then
            echo ::set-output name=release_all::true
          else
            env=$(awk -F- '{print $2}' <<< '${{steps.latest-release.outputs.tag_name}}')
            echo env:: $env

            this_release=$(git tag | grep $env | sed '1!G;h;$!d' | head -n 1)
            echo This release version: $this_release

            echo ::set-output name=this_sha::$(git rev-list -n 1 $this_release)

            previous_release=$(git tag | grep $env | sed '1!G;h;$!d' | head -n 2 | tail -1)
            echo Previous release version:: $previous_release

            if [[ -z $previous_release ]] ; then
              echo This is the first release. Getting the first commit sha.
              echo ::set-output name=that_sha::$(git rev-list --max-parents=0 HEAD)
            else
              echo ::set-output name=that_sha::$(git rev-list -n 1 $previous_release)
            fi
          fi

      - name: Deploy
        run: |
          if [[ "${{steps.vars.outputs.release_all}}" = "true" ]]; then
            nx run-many --target=deploy --all
          else
            nx affected --target=deploy --base=${{steps.vars.outputs.that_sha}} --head=${{steps.vars.outputs.this_sha}}
          fi
